<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ZeXin Chen">
<meta name="dcterms.date" content="2026-09-10">

<title>Hands-on Exercise 3 – ISSS626-GAA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9d96f532d65220ca877c0304385df42f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;family=Newsreader:opsz,wght@6..72,400;6..72,600&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#loading-the-packages" id="toc-loading-the-packages" class="nav-link" data-scroll-target="#loading-the-packages"><span class="header-section-number">2</span> Loading the Packages</a></li>
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data"><span class="header-section-number">3</span> Preparing the Data</a>
  <ul class="collapse">
  <li><a href="#importing-and-preparing-study-area" id="toc-importing-and-preparing-study-area" class="nav-link" data-scroll-target="#importing-and-preparing-study-area"><span class="header-section-number">3.1</span> Importing and Preparing Study Area</a></li>
  <li><a href="#importing-and-preparing-forest-fire-data" id="toc-importing-and-preparing-forest-fire-data" class="nav-link" data-scroll-target="#importing-and-preparing-forest-fire-data"><span class="header-section-number">3.2</span> Importing and Preparing Forest Fire Data</a></li>
  </ul></li>
  <li><a href="#visualising-the-fire-points" id="toc-visualising-the-fire-points" class="nav-link" data-scroll-target="#visualising-the-fire-points"><span class="header-section-number">4</span> Visualising the Fire Points</a>
  <ul class="collapse">
  <li><a href="#overall-plot" id="toc-overall-plot" class="nav-link" data-scroll-target="#overall-plot"><span class="header-section-number">4.1</span> Overall Plot</a></li>
  <li><a href="#visualising-geographic-distribution-of-forest-fires-by-month" id="toc-visualising-geographic-distribution-of-forest-fires-by-month" class="nav-link" data-scroll-target="#visualising-geographic-distribution-of-forest-fires-by-month"><span class="header-section-number">4.2</span> Visualising Geographic Distribution of Forest Fires by Month</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-month" id="toc-computing-stkde-by-month" class="nav-link" data-scroll-target="#computing-stkde-by-month"><span class="header-section-number">5</span> Computing STKDE by Month</a>
  <ul class="collapse">
  <li><a href="#creating-ppp-and-including-owin-object" id="toc-creating-ppp-and-including-owin-object" class="nav-link" data-scroll-target="#creating-ppp-and-including-owin-object"><span class="header-section-number">5.1</span> Creating ppp and Including Owin Object</a></li>
  <li><a href="#computing-spatio-temporal-kde" id="toc-computing-spatio-temporal-kde" class="nav-link" data-scroll-target="#computing-spatio-temporal-kde"><span class="header-section-number">5.2</span> Computing Spatio-Temporal KDE</a></li>
  <li><a href="#plotting-the-spatio-temporal-kde-object" id="toc-plotting-the-spatio-temporal-kde-object" class="nav-link" data-scroll-target="#plotting-the-spatio-temporal-kde-object"><span class="header-section-number">5.3</span> Plotting the Spatio-Temporal KDE Object</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-day-of-year" id="toc-computing-stkde-by-day-of-year" class="nav-link" data-scroll-target="#computing-stkde-by-day-of-year"><span class="header-section-number">6</span> Computing STKDE by Day of Year</a>
  <ul class="collapse">
  <li><a href="#computing-spatio-temporal-kde-1" id="toc-computing-spatio-temporal-kde-1" class="nav-link" data-scroll-target="#computing-spatio-temporal-kde-1"><span class="header-section-number">6.1</span> Computing Spatio-Temporal KDE</a></li>
  <li><a href="#plotting-the-spatio-temporal-kde-object-1" id="toc-plotting-the-spatio-temporal-kde-object-1" class="nav-link" data-scroll-target="#plotting-the-spatio-temporal-kde-object-1"><span class="header-section-number">6.2</span> Plotting the Spatio-Temporal KDE Object</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-day-of-year-improved-method" id="toc-computing-stkde-by-day-of-year-improved-method" class="nav-link" data-scroll-target="#computing-stkde-by-day-of-year-improved-method"><span class="header-section-number">7</span> Computing STKDE by Day of Year: Improved Method</a>
  <ul class="collapse">
  <li><a href="#computing-spatio-temporal-kde-2" id="toc-computing-spatio-temporal-kde-2" class="nav-link" data-scroll-target="#computing-spatio-temporal-kde-2"><span class="header-section-number">7.1</span> Computing Spatio-Temporal KDE</a></li>
  <li><a href="#plotting-the-output-spatio-temporal-kde" id="toc-plotting-the-output-spatio-temporal-kde" class="nav-link" data-scroll-target="#plotting-the-output-spatio-temporal-kde"><span class="header-section-number">7.2</span> Plotting the Output Spatio-Temporal KDE</a></li>
  </ul></li>
  <li><a href="#spatio-temporal-point-patterns-analysis-stpp-methods" id="toc-spatio-temporal-point-patterns-analysis-stpp-methods" class="nav-link" data-scroll-target="#spatio-temporal-point-patterns-analysis-stpp-methods"><span class="header-section-number">8</span> Spatio-Temporal Point Patterns Analysis: stpp Methods</a>
  <ul class="collapse">
  <li><a href="#preparing-spatio-temporal-point-process-object-of-stpp" id="toc-preparing-spatio-temporal-point-process-object-of-stpp" class="nav-link" data-scroll-target="#preparing-spatio-temporal-point-process-object-of-stpp"><span class="header-section-number">8.1</span> Preparing Spatio-Temporal Point Process Object of stpp</a></li>
  <li><a href="#computing-spatio-temporal-k-function" id="toc-computing-spatio-temporal-k-function" class="nav-link" data-scroll-target="#computing-spatio-temporal-k-function"><span class="header-section-number">8.2</span> Computing Spatio-Temporal K-Function</a></li>
  <li><a href="#guide-to-interpreting-the-plot" id="toc-guide-to-interpreting-the-plot" class="nav-link" data-scroll-target="#guide-to-interpreting-the-plot"><span class="header-section-number">8.3</span> Guide to Interpreting the Plot</a></li>
  </ul></li>
  <li><a href="#beyond-the-exercise" id="toc-beyond-the-exercise" class="nav-link" data-scroll-target="#beyond-the-exercise"><span class="header-section-number">9</span> Beyond the Exercise</a>
  <ul class="collapse">
  <li><a href="#does-the-type-filter-change-the-answer" id="toc-does-the-type-filter-change-the-answer" class="nav-link" data-scroll-target="#does-the-type-filter-change-the-answer"><span class="header-section-number">9.1</span> Does the Type Filter Change the Answer</a></li>
  <li><a href="#does-detection-confidence-change-the-answer" id="toc-does-detection-confidence-change-the-answer" class="nav-link" data-scroll-target="#does-detection-confidence-change-the-answer"><span class="header-section-number">9.2</span> Does Detection Confidence Change the Answer</a></li>
  <li><a href="#is-it-space-time-or-both" id="toc-is-it-space-time-or-both" class="nav-link" data-scroll-target="#is-it-space-time-or-both"><span class="header-section-number">9.3</span> Is It Space, Time, or Both</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">10</span> Limitations</a></li>
  <li><a href="#reflections" id="toc-reflections" class="nav-link" data-scroll-target="#reflections"><span class="header-section-number">11</span> Reflections</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 3</h1>
<p class="subtitle lead">Spatio-Temporal Point Patterns Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ZeXin Chen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 10, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 23, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="pagefacts">
<p><span class="fact">Two datasets, both global, both filtered to one province</span> <span class="fact data">NASA FIRMS MODIS 2023, GADM 4.1 level 2</span> <span class="fact pkg"><code>sf</code> <code>spatstat</code> <code>sparr</code> <code>stpp</code> <code>tmap</code> <code>tidyverse</code></span></p>
</div>
<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>Exercises 1 and 2 treated every point as if it happened at the same instant. This one adds time. A fire on 3 August and a fire on 4 August a kilometre apart are a different pattern from the same two fires six months apart, and the methods here can tell them apart.</p>
<p>The two questions the chapter asks are simple. Are the fires in Kepulauan Bangka Belitung independent in space and time, and if not, where and when do they cluster.</p>
</section>
<section id="loading-the-packages" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Loading the Packages</h1>
<p>Six packages, two of them new. <strong>sf</strong> reads and transforms the boundary and the fire points. <strong>spatstat</strong> supplies the <code>ppp</code> and <code>owin</code> objects and the L function envelope. <strong>sparr</strong> computes the spatio-temporal kernel density and picks its bandwidths. <strong>stpp</strong> computes the spatio-temporal K function. <strong>tmap</strong> draws the point maps. <strong>tidyverse</strong> does the reading, filtering and counting.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spatstat, sparr, stpp, tmap, tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Issue I hit
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>sparr</code> refused to load on my Mac. It pulls in a package called <code>rpanel</code> that wants X11, which Apple stopped shipping years ago.</p>
<p>The fix is XQuartz, then logging out and back in so the display variable gets set. After that it loads with a warning about display <code>:0</code> that can be ignored. None of the X11 machinery is used for anything in this exercise. It is only there so <code>rpanel</code> can draw sliders I will never open.</p>
</div>
</div>
</section>
<section id="preparing-the-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Preparing the Data</h1>
<section id="importing-and-preparing-study-area" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="importing-and-preparing-study-area"><span class="header-section-number">3.1</span> Importing and Preparing Study Area</h2>
<p>The book uses a kelurahan shapefile from an Indonesian portal. That download ran at 44 kilobytes a second on the day I tried it, with three hours on the clock for 553 MB. I used GADM level 2 instead, which is regency boundaries for the whole country in 4.6 MB.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Importing the study area</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Converting to owin</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p><code>st_read()</code> of <strong>sf</strong> reads the national GADM file. The chain then keeps the province, merges it into one outline, drops the Z dimension and projects it to UTM.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>kbb_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/rawdata/gadm/gadm41_IDN_2.json"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME_1 <span class="sc">==</span> <span class="st">"BangkaBelitung"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_zm</span>(<span class="at">drop =</span> <span class="cn">TRUE</span>, <span class="at">what =</span> <span class="st">"ZM"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gadm41_IDN_2' from data source 
  `/Users/czxtom/Documents/Programming/GAA/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex03/data/rawdata/gadm/gadm41_IDN_2.json' 
  using driver `GeoJSON'
Simple feature collection with 502 features and 13 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 95.0102 ymin: -11.0075 xmax: 141.0194 ymax: 6.0766
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three things in that chain.</p>
<p>The province name in GADM is <code>BangkaBelitung</code>, no space. I found that by printing the unique values rather than guessing, which saved a silent empty filter.</p>
<p><code>st_union()</code> merges the seven level-2 units (six regencies and the city of Pangkal Pinang) into one outline. Since the rest of the exercise only needs the outer boundary, the admin level underneath does not matter. Kelurahan, kecamatan, kabupaten, all merge to the same shape.</p>
<p>And the CRS is 32748, not 3414. That is UTM zone 48 south. Bangka Belitung sits at 106 east and 2 south, which puts it in zone 48, and the S is because it is below the equator. Using Singapore’s SVY21 here would put the whole island somewhere it is not.</p>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><code>as.owin()</code> of <strong>spatstat</strong> turns the merged outline into an observation window, the object every point pattern below gets clipped to.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>kbb_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(kbb_sf)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(kbb_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "owin"</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>A quick <code>plot()</code> of the window checks that the union and the projection both worked before any points go on it.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.main =</span> <span class="fl">1.3</span>, <span class="at">cex.sub =</span> <span class="fl">1.1</span>, <span class="at">cex.lab =</span> <span class="fl">1.1</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kbb_owin, <span class="at">main =</span> <span class="st">"Kepulauan Bangka Belitung, the observation window"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#EFE9DB"</span>, <span class="at">border =</span> <span class="st">"grey40"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="importing-and-preparing-forest-fire-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="importing-and-preparing-forest-fire-data"><span class="header-section-number">3.2</span> Importing and Preparing Forest Fire Data</h2>
<p>FIRMS publishes MODIS detections one file per country per year. The whole-countries bundle I tried first arrived truncated at 43 of 82 MB and Indonesia was in the missing part, so I fetched the Indonesia file directly instead.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Importing the Indonesia file</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Checking the type column</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><code>read_csv()</code> of <strong>readr</strong> (part of <strong>tidyverse</strong>) reads the file, and <code>nrow()</code> counts the rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fire_all <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rawdata/modis/modis_2023_Indonesia.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52156</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>That is every detection in Indonesia for 2023. Before clipping to the study area, one column the book never mentions. <code>table()</code> counts the rows of each <code>type</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(fire_all<span class="sc">$</span>type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1     2     3 
47883  1495  2755    23 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Where I differ from the book
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book keeps every row and calls them forest fires. The <code>type</code> column says otherwise.</p>
<p>Type 0 is a presumed vegetation fire. Type 1 is an active volcano. Type 2 is another static land source, which means gas flares, industrial heat, that kind of thing. Type 3 is offshore. Indonesia has a lot of volcanoes and a lot of flares, and 4,250 of these detections are one or the other (1,495 volcano, 2,755 static source), with another 23 offshore.</p>
<p>A volcano showing up every day at the same spot would look like extreme spatio-temporal clustering. It is, but not of fires. I keep type 0 only.</p>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Filtering and clipping</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Deriving the time fields</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p><code>filter()</code> keeps type 0, <code>st_as_sf()</code> turns the longitude and latitude into points, <code>st_transform()</code> projects them to the same UTM zone as the boundary, and <code>st_filter()</code> of <strong>sf</strong> keeps only the points inside Bangka Belitung.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_all <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(type <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_filter</span>(<span class="fu">st_as_sf</span>(kbb_sf))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fire_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 897</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book’s csv was already cut to Bangka Belitung, so it has no clipping step. Mine is all of Indonesia, so <code>st_filter()</code> does the cut. It keeps points that intersect the boundary polygon and drops the rest.</p>
<p>I checked the count against the book’s 741. Mine is different, and it should be. Different boundary source, and the type filter removed one static-source row that the book’s approach would have kept.</p>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p><code>as.ppp()</code> only accepts numbers or text as marks, so the date has to become a number. <code>yday()</code> and <code>month()</code> of <strong>lubridate</strong> (part of <strong>tidyverse</strong>) give three versions, for three different uses later.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">acq_date =</span> <span class="fu">as.Date</span>(acq_date),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">DayofYear =</span> <span class="fu">yday</span>(acq_date),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month_num =</span> <span class="fu">month</span>(acq_date),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month_fac =</span> <span class="fu">month</span>(acq_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="visualising-the-fire-points" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Visualising the Fire Points</h1>
<section id="overall-plot" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="overall-plot"><span class="header-section-number">4.1</span> Overall Plot</h2>
<p><code>tm_shape()</code> and <code>tm_dots()</code> of <strong>tmap</strong> put every 2023 detection on the merged outline.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"#F7F4EC"</span>, <span class="at">col =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">fill_alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"MODIS fire detections, Bangka Belitung, 2023"</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_credits</span>(<span class="st">"Source: NASA FIRMS, GADM"</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="visualising-geographic-distribution-of-forest-fires-by-month" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="visualising-geographic-distribution-of-forest-fires-by-month"><span class="header-section-number">4.2</span> Visualising Geographic Distribution of Forest Fires by Month</h2>
<p>Now by month, which is where the time dimension first shows. <code>tm_facets()</code> of <strong>tmap</strong> splits the same map into one panel per value of <code>Month_fac</code>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"#F7F4EC"</span>, <span class="at">col =</span> <span class="st">"grey70"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">fill_alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"Month_fac"</span>, <span class="at">free.coords =</span> <span class="cn">FALSE</span>, <span class="at">drop.units =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Fires by month, the dry season lights up from July"</span>, <span class="at">size =</span> <span class="fl">1.3</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">panel.label.size =</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>To put numbers on the panels, <code>st_drop_geometry()</code> strips the points back to a table and <code>count()</code> tallies the detections per month.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Month_fac, <span class="at">name =</span> <span class="st">"fires"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   Month_fac fires
   &lt;ord&gt;     &lt;int&gt;
 1 January      11
 2 February      4
 3 March        12
 4 April        10
 5 May          24
 6 June         40
 7 July         92
 8 August      167
 9 September   183
10 October     239
11 November    103
12 December     12</code></pre>
</div>
</div>
<p>The first half of the year is nearly empty, 101 of the 897 detections, and August to October carry most of the fires, 589 of them. That is the dry season, and it is the first hint that time matters at least as much as location here.</p>
</section>
</section>
<section id="computing-stkde-by-month" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Computing STKDE by Month</h1>
<p>Exercise 2’s KDE gave one density surface for the whole year. Here there is one surface for every point in time, so the estimate at any location depends on how many fires happened nearby <em>and</em> recently.</p>
<section id="creating-ppp-and-including-owin-object" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="creating-ppp-and-including-owin-object"><span class="header-section-number">5.1</span> Creating ppp and Including Owin Object</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">Creating the ppp inside the owin</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">Checking for duplicates</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p><code>as.ppp()</code> of <strong>spatstat</strong> turns the points into a point pattern with <code>Month_num</code> as the mark, and indexing it by <code>kbb_owin</code> clips it to the observation window.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fire_month_ppp <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Month_num) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>fire_month_owin <span class="ot">&lt;-</span> fire_month_ppp[kbb_owin]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  897 points
Average intensity 5.35172e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   8.000   9.000   8.639  10.000  12.000 

Window: polygonal boundary
308 separate polygons (38 holes)
                   vertices         area relative.area
polygon 1               815  1.16029e+10      6.92e-01
polygon 2                 3  3.24609e+04      1.94e-06
polygon 3                 4  5.42232e+04      3.24e-06
polygon 4                 4  7.99416e+03      4.77e-07
polygon 5                 4  6.30175e+04      3.76e-06
polygon 6                 5  3.82047e+05      2.28e-05
polygon 7                 4  2.39770e+04      1.43e-06
polygon 8                 5  2.22126e+05      1.33e-05
polygon 9 (hole)          3 -3.67129e+04     -2.19e-06
polygon 10 (hole)         3 -3.42876e+04     -2.05e-06
polygon 11                7  1.20124e+06      7.17e-05
polygon 12 (hole)         3 -4.25631e+03     -2.54e-07
polygon 13 (hole)         4 -4.66781e+04     -2.78e-06
polygon 14 (hole)         3 -1.68389e+04     -1.00e-06
polygon 15 (hole)         3 -7.27168e+02     -4.34e-08
polygon 16 (hole)         3 -2.79621e+04     -1.67e-06
polygon 17 (hole)         3 -6.60375e+02     -3.94e-08
polygon 18 (hole)         3 -2.52842e+03     -1.51e-07
polygon 19 (hole)         3 -1.38314e+03     -8.25e-08
polygon 20               11  1.20884e+06      7.21e-05
polygon 21 (hole)         3 -3.27585e+04     -1.95e-06
polygon 22                5  1.74926e+05      1.04e-05
polygon 23 (hole)         3 -3.35348e+02     -2.00e-08
polygon 24 (hole)         3 -4.08226e+03     -2.44e-07
polygon 25 (hole)         3 -1.45480e+04     -8.68e-07
polygon 26 (hole)         3 -3.08962e+02     -1.84e-08
polygon 27                6  1.40188e+05      8.36e-06
polygon 28                5  8.49109e+04      5.07e-06
polygon 29                4  2.39803e+03      1.43e-07
polygon 30                4  8.73093e+03      5.21e-07
polygon 31                5  1.29977e+05      7.75e-06
polygon 32                4  8.60809e+03      5.14e-07
polygon 33                5  2.59087e+05      1.55e-05
polygon 34                4  1.58516e+05      9.46e-06
polygon 35                4  1.29123e+03      7.70e-08
polygon 36                5  1.10066e+05      6.57e-06
polygon 37                4  2.21238e+03      1.32e-07
polygon 38                8  1.54252e+05      9.20e-06
polygon 39                4  8.48082e+03      5.06e-07
polygon 40                4  2.33528e+03      1.39e-07
polygon 41               15  3.11417e+06      1.86e-04
polygon 42               11  2.31185e+06      1.38e-04
polygon 43                4  6.36935e+04      3.80e-06
polygon 44                4  3.76206e+04      2.24e-06
polygon 45                4  6.32582e+04      3.77e-06
polygon 46                4  1.25637e+04      7.50e-07
polygon 47              662  4.61716e+09      2.75e-01
polygon 48                4  6.34172e+03      3.78e-07
polygon 49                5  1.20592e+05      7.19e-06
polygon 50                4  1.73619e+04      1.04e-06
polygon 51                4  2.77155e+04      1.65e-06
polygon 52                5  6.42757e+04      3.83e-06
polygon 53                4  8.43501e+03      5.03e-07
polygon 54                4  7.51117e+03      4.48e-07
polygon 55                9  1.46680e+06      8.75e-05
polygon 56                5  3.36169e+04      2.01e-06
polygon 57                4  6.05506e+04      3.61e-06
polygon 58                4  1.16395e+04      6.94e-07
polygon 59                4  4.13323e+04      2.47e-06
polygon 60                4  1.07759e+04      6.43e-07
polygon 61                4  3.81773e+03      2.28e-07
polygon 62                4  1.67345e+05      9.98e-06
polygon 63                4  3.08386e+04      1.84e-06
polygon 64                4  5.78820e+03      3.45e-07
polygon 65                4  5.41829e+03      3.23e-07
polygon 66                4  2.21673e+03      1.32e-07
polygon 67                4  1.63779e+04      9.77e-07
polygon 68                4  7.63485e+03      4.56e-07
polygon 69                4  8.68147e+03      5.18e-07
polygon 70                4  7.26509e+03      4.33e-07
polygon 71                4  1.02214e+04      6.10e-07
polygon 72                4  1.98251e+04      1.18e-06
polygon 73                4  8.61964e+03      5.14e-07
polygon 74                4  8.19962e+04      4.89e-06
polygon 75                4  3.32475e+03      1.98e-07
polygon 76                4  2.77069e+03      1.65e-07
polygon 77                4  3.94077e+03      2.35e-07
polygon 78                4  6.38963e+04      3.81e-06
polygon 79                4  2.58576e+03      1.54e-07
polygon 80 (hole)         3 -4.14788e+03     -2.47e-07
polygon 81                4  7.20362e+03      4.30e-07
polygon 82                4  6.09823e+03      3.64e-07
polygon 83                4  4.80847e+04      2.87e-06
polygon 84                5  2.12649e+05      1.27e-05
polygon 85 (hole)         4 -1.54678e+04     -9.23e-07
polygon 86                8  1.12373e+06      6.70e-05
polygon 87                4  2.52418e+03      1.51e-07
polygon 88                4  5.29463e+03      3.16e-07
polygon 89                4  7.57252e+03      4.52e-07
polygon 90                6  1.64502e+05      9.81e-06
polygon 91                4  5.95010e+04      3.55e-06
polygon 92                4  1.21987e+04      7.28e-07
polygon 93                4  7.38787e+02      4.41e-08
polygon 94                4  2.73952e+04      1.63e-06
polygon 95                4  4.00173e+03      2.39e-07
polygon 96                4  2.89358e+03      1.73e-07
polygon 97                4  4.37124e+03      2.61e-07
polygon 98 (hole)         3 -1.28102e+04     -7.64e-07
polygon 99               10  2.18651e+06      1.30e-04
polygon 100               4  4.09041e+04      2.44e-06
polygon 101               4  4.18641e+03      2.50e-07
polygon 102               4  1.00965e+04      6.02e-07
polygon 103 (hole)        3 -1.25852e+03     -7.51e-08
polygon 104               4  9.48097e+03      5.66e-07
polygon 105               4  6.97619e+04      4.16e-06
polygon 106               4  1.41599e+03      8.45e-08
polygon 107 (hole)        3 -5.96762e+04     -3.56e-06
polygon 108 (hole)        3 -5.49663e+04     -3.28e-06
polygon 109               4  3.36485e+04      2.01e-06
polygon 110               6  5.27406e+05      3.15e-05
polygon 111               4  4.88529e+04      2.91e-06
polygon 112               5  7.28786e+04      4.35e-06
polygon 113              12  1.03353e+06      6.17e-05
polygon 114               7  2.21577e+05      1.32e-05
polygon 115               4  3.47765e+04      2.07e-06
polygon 116 (hole)        4 -2.29935e+04     -1.37e-06
polygon 117               6  8.13353e+05      4.85e-05
polygon 118 (hole)        3 -3.04392e+04     -1.82e-06
polygon 119               4  4.24745e+03      2.53e-07
polygon 120               4  1.01108e+05      6.03e-06
polygon 121               4  9.41820e+03      5.62e-07
polygon 122               4  1.09569e+04      6.54e-07
polygon 123               4  1.23116e+02      7.35e-09
polygon 124 (hole)        3 -5.35156e+03     -3.19e-07
polygon 125              15  3.89941e+05      2.33e-05
polygon 126 (hole)        3 -1.72223e+04     -1.03e-06
polygon 127               4  2.55805e+04      1.53e-06
polygon 128               8  1.04148e+05      6.21e-06
polygon 129               5  7.50943e+03      4.48e-07
polygon 130               7  4.55629e+05      2.72e-05
polygon 131 (hole)        3 -9.54582e+03     -5.70e-07
polygon 132               4  1.55105e+04      9.25e-07
polygon 133               4  1.76039e+04      1.05e-06
polygon 134               4  5.35495e+03      3.19e-07
polygon 135               4  4.43060e+03      2.64e-07
polygon 136               5  4.06734e+05      2.43e-05
polygon 137              45  1.76360e+07      1.05e-03
polygon 138               4  7.01667e+03      4.19e-07
polygon 139               4  4.25343e+03      2.54e-07
polygon 140               5  2.11664e+05      1.26e-05
polygon 141               4  1.84588e+03      1.10e-07
polygon 142               5  5.00832e+03      2.99e-07
polygon 143               5  7.62514e+04      4.55e-06
polygon 144               4  3.63039e+03      2.17e-07
polygon 145              50  4.89627e+07      2.92e-03
polygon 146             111  1.19754e+08      7.14e-03
polygon 147              16  3.68174e+06      2.20e-04
polygon 148               4  8.24760e+04      4.92e-06
polygon 149               5  5.81024e+04      3.47e-06
polygon 150               4  4.08073e+04      2.43e-06
polygon 151               4  2.89845e+04      1.73e-06
polygon 152               8  1.43483e+06      8.56e-05
polygon 153               4  1.20814e+04      7.21e-07
polygon 154              13  3.67004e+06      2.19e-04
polygon 155              14  3.63429e+06      2.17e-04
polygon 156               4  2.24611e+04      1.34e-06
polygon 157               4  1.55087e+04      9.25e-07
polygon 158               4  2.11021e+05      1.26e-05
polygon 159               4  5.23124e+03      3.12e-07
polygon 160               4  5.60046e+03      3.34e-07
polygon 161               4  1.37815e+04      8.22e-07
polygon 162              19  7.13461e+06      4.26e-04
polygon 163 (hole)        3 -5.67120e+03     -3.38e-07
polygon 164 (hole)        4 -1.00459e+05     -5.99e-06
polygon 165 (hole)        3 -5.37996e+03     -3.21e-07
polygon 166 (hole)        3 -1.82674e+04     -1.09e-06
polygon 167               5  1.38061e+05      8.24e-06
polygon 168 (hole)        3 -3.74646e+04     -2.24e-06
polygon 169 (hole)        3 -3.01697e+04     -1.80e-06
polygon 170 (hole)        3 -5.28210e+04     -3.15e-06
polygon 171               9  1.97808e+06      1.18e-04
polygon 172               4  1.58607e+04      9.46e-07
polygon 173              74  2.12604e+08      1.27e-02
polygon 174               5  1.62979e+05      9.72e-06
polygon 175               4  4.30659e+03      2.57e-07
polygon 176               9  1.53324e+06      9.15e-05
polygon 177               4  9.59752e+03      5.73e-07
polygon 178               4  4.79930e+04      2.86e-06
polygon 179              52  2.23528e+07      1.33e-03
polygon 180              16  2.45920e+06      1.47e-04
polygon 181               4  8.13532e+03      4.85e-07
polygon 182               4  3.38408e+04      2.02e-06
polygon 183               4  2.41837e+04      1.44e-06
polygon 184               4  5.16830e+03      3.08e-07
polygon 185               5  1.61814e+04      9.65e-07
polygon 186               4  6.27571e+03      3.74e-07
polygon 187               5  9.84176e+05      5.87e-05
polygon 188               6  4.20332e+05      2.51e-05
polygon 189               4  2.80854e+05      1.68e-05
polygon 190              10  1.12068e+06      6.69e-05
polygon 191               6  6.73527e+05      4.02e-05
polygon 192               4  4.54882e+04      2.71e-06
polygon 193              12  5.21902e+06      3.11e-04
polygon 194              18  1.73578e+06      1.04e-04
polygon 195               4  3.38083e+04      2.02e-06
polygon 196               4  1.26951e+04      7.57e-07
polygon 197               4  3.62554e+03      2.16e-07
polygon 198              12  3.09025e+06      1.84e-04
polygon 199               4  1.47390e+05      8.79e-06
polygon 200               5  4.05411e+05      2.42e-05
polygon 201               4  4.33229e+04      2.58e-06
polygon 202               5  1.11261e+05      6.64e-06
polygon 203               4  2.74282e+04      1.64e-06
polygon 204              10  1.68501e+06      1.01e-04
polygon 205 (hole)        3 -6.11140e+04     -3.65e-06
polygon 206               4  1.53224e+05      9.14e-06
polygon 207               4  1.93211e+04      1.15e-06
polygon 208               9  1.84908e+06      1.10e-04
polygon 209 (hole)        3 -1.33518e+04     -7.97e-07
polygon 210               4  4.12824e+04      2.46e-06
polygon 211               9  1.09964e+06      6.56e-05
polygon 212               7  8.26344e+05      4.93e-05
polygon 213              13  3.94567e+06      2.35e-04
polygon 214               9  7.82390e+05      4.67e-05
polygon 215               4  4.42404e+04      2.64e-06
polygon 216 (hole)        3 -1.04577e+04     -6.24e-07
polygon 217               4  4.24176e+03      2.53e-07
polygon 218               6  6.77188e+05      4.04e-05
polygon 219               5  3.74156e+05      2.23e-05
polygon 220               4  5.16401e+03      3.08e-07
polygon 221               4  3.24186e+04      1.93e-06
polygon 222              18  7.37432e+06      4.40e-04
polygon 223               5  2.31557e+05      1.38e-05
polygon 224               4  8.61269e+03      5.14e-07
polygon 225               4  9.72139e+03      5.80e-07
polygon 226               4  4.63359e+04      2.76e-06
polygon 227               5  7.51106e+04      4.48e-06
polygon 228               4  5.80096e+04      3.46e-06
polygon 229               4  1.32885e+04      7.93e-07
polygon 230               4  2.83028e+03      1.69e-07
polygon 231               4  2.57186e+04      1.53e-06
polygon 232               5  4.18863e+05      2.50e-05
polygon 233               3  1.72258e+03      1.03e-07
polygon 234               4  2.58773e+03      1.54e-07
polygon 235               4  1.53801e+03      9.18e-08
polygon 236               4  1.20582e+04      7.19e-07
polygon 237               4  1.63886e+04      9.78e-07
polygon 238               4  2.67587e+04      1.60e-06
polygon 239               4  1.59792e+03      9.53e-08
polygon 240               4  2.82709e+03      1.69e-07
polygon 241               4  3.99475e+03      2.38e-07
polygon 242               4  1.47504e+03      8.80e-08
polygon 243              17  3.84724e+06      2.30e-04
polygon 244               4  2.82673e+03      1.69e-07
polygon 245               4  1.01394e+04      6.05e-07
polygon 246 (hole)        7 -6.43668e+04     -3.84e-06
polygon 247 (hole)        3 -9.40962e+01     -5.61e-09
polygon 248               4  1.10610e+04      6.60e-07
polygon 249               4  1.74517e+04      1.04e-06
polygon 250               4  2.82669e+03      1.69e-07
polygon 251               7  5.06540e+05      3.02e-05
polygon 252               4  6.29591e+04      3.76e-06
polygon 253               4  4.54585e+04      2.71e-06
polygon 254               6  9.55597e+05      5.70e-05
polygon 255               7  7.76558e+05      4.63e-05
polygon 256               5  1.71781e+05      1.02e-05
polygon 257               5  2.11515e+05      1.26e-05
polygon 258               7  2.87493e+05      1.72e-05
polygon 259               5  3.95557e+05      2.36e-05
polygon 260              27  1.62392e+07      9.69e-04
polygon 261               4  4.43585e+03      2.65e-07
polygon 262               4  6.27477e+03      3.74e-07
polygon 263              10  1.30987e+06      7.82e-05
polygon 264               9  2.25682e+06      1.35e-04
polygon 265               4  1.45948e+04      8.71e-07
polygon 266               4  1.21931e+04      7.27e-07
polygon 267               9  1.17483e+06      7.01e-05
polygon 268               4  2.20546e+04      1.32e-06
polygon 269               5  3.03395e+04      1.81e-06
polygon 270               4  9.35222e+03      5.58e-07
polygon 271               4  1.03499e+05      6.18e-06
polygon 272               6  2.34707e+04      1.40e-06
polygon 273               4  7.75326e+03      4.63e-07
polygon 274               4  1.23210e+03      7.35e-08
polygon 275               4  2.71061e+03      1.62e-07
polygon 276               4  2.80917e+04      1.68e-06
polygon 277               4  1.97108e+03      1.18e-07
polygon 278               4  4.43561e+03      2.65e-07
polygon 279               4  5.11117e+03      3.05e-07
polygon 280               6  4.86779e+05      2.90e-05
polygon 281               5  8.12261e+04      4.85e-06
polygon 282               4  2.50739e+04      1.50e-06
polygon 283               4  2.71022e+03      1.62e-07
polygon 284               6  3.33963e+05      1.99e-05
polygon 285              14  3.34010e+06      1.99e-04
polygon 286               4  4.31165e+03      2.57e-07
polygon 287               4  2.84259e+04      1.70e-06
polygon 288               4  2.50478e+04      1.49e-06
polygon 289               5  1.72690e+05      1.03e-05
polygon 290               4  1.37933e+04      8.23e-07
polygon 291               4  3.08058e+03      1.84e-07
polygon 292               5  1.34807e+05      8.04e-06
polygon 293               5  4.43080e+04      2.64e-06
polygon 294              13  2.22861e+06      1.33e-04
polygon 295               4  4.19032e+03      2.50e-07
polygon 296              11  1.04351e+06      6.23e-05
polygon 297               4  1.49419e+04      8.91e-07
polygon 298               4  7.14815e+03      4.26e-07
polygon 299               4  8.08482e+04      4.82e-06
polygon 300               6  1.92382e+05      1.15e-05
polygon 301               4  2.08873e+05      1.25e-05
polygon 302               4  3.08068e+04      1.84e-06
polygon 303               5  6.62422e+04      3.95e-06
polygon 304               7  1.05373e+06      6.29e-05
polygon 305               4  2.57200e+04      1.53e-06
polygon 306               4  1.22325e+05      7.30e-06
polygon 307               6  2.33212e+05      1.39e-05
polygon 308               4  1.44038e+05      8.59e-06
enclosing rectangle: [512010.2, 928094.9] x [9621873, 9833973] units
                     (416100 x 212100 units)
Window area = 1.6761e+10 square units
Fraction of frame area: 0.19</code></pre>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p><code>duplicated()</code> flags points that share both location and mark, which kernel estimators handle badly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(fire_month_owin))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="computing-spatio-temporal-kde" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="computing-spatio-temporal-kde"><span class="header-section-number">5.2</span> Computing Spatio-Temporal KDE</h2>
<p><code>spattemp.density()</code> of <strong>sparr</strong> estimates the density over space and time with its default bandwidths, and <code>summary()</code> prints them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_month_owin)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(st_kde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 19139.22 (spatial)
  lambda = 0.0265 (temporal)

No. of observations
  897 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.2, 928094.9] x [9621873, 9833973]

Temporal bound
  [1, 12]

Evaluation
  128 x 128 x 12 trivariate lattice
  Density range: [1.404024e-39, 6.38687e-10]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two bandwidths come out of this, not one. <code>h</code> is the spatial one in metres, around 19 km. <code>lambda</code> is the temporal one in months, and it comes out at 0.027 of a month, which is less than a day.</p>
<p>A day of smoothing on data recorded in whole months is odd. It means month 8 barely borrows anything from months 7 or 9.</p>
<p>I did not understand why until the day-of-year section below, where the same function picks a very different lambda. The default rule reacts to how the time values are spaced, and whole months are very coarse.</p>
</div>
</div>
</section>
<section id="plotting-the-spatio-temporal-kde-object" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="plotting-the-spatio-temporal-kde-object"><span class="header-section-number">5.3</span> Plotting the Spatio-Temporal KDE Object</h2>
<p><strong>sparr</strong>’s <code>plot()</code> method draws one time slice per call. It also adds <code>axis(1)</code>, <code>axis(2)</code> and an L-shaped box after every panel, so my first version framed each small map in projected metres like 9.7e+06, which mean nothing to a reader and got cut off at the panel edges. The small function below does what that method does, one slice drawn with <strong>spatstat</strong>’s <code>plot()</code> for pixel images plus the window outline, just without the axes. It takes the colour range as an argument so that panels can share one scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plot_slice <span class="ot">&lt;-</span> <span class="cf">function</span>(kde, t, zlim, main) {</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  tt <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(kde<span class="sc">$</span>z))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  slice <span class="ot">&lt;-</span> kde<span class="sc">$</span>z[[<span class="fu">which.min</span>(<span class="fu">abs</span>(tt <span class="sc">-</span> t))]]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(slice, <span class="at">main =</span> main, <span class="at">zlim =</span> zlim, <span class="at">box =</span> <span class="cn">FALSE</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">ribargs =</span> <span class="fu">list</span>(<span class="at">box =</span> <span class="cn">TRUE</span>))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">as.polygonal</span>(<span class="fu">Window</span>(kde<span class="sc">$</span>pp)), <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>The obvious fix, <code>par(xaxt = "n", yaxt = "n")</code> before the loop, would also have blanked the numbers on the colour ribbon. spatstat draws those with <code>axis()</code> on side 4, and a global <code>yaxt = "n"</code> switches that off too. Reading the source of <code>plot.stden()</code> showed it is a short loop around a <code>plot.im()</code> call, so copying the two lines I needed was simpler than fighting the axes.</p>
</div>
</div>
<p>The panels show July to December. The colour key is the estimated joint density, the share of the year’s detections per square metre per month, which is why the numbers are so small (the peak is about 6.4e-10). <code>zlim_month</code> is the range over all twelve monthly surfaces, so the six panels share one colour scale.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>zlim_month <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">sapply</span>(st_kde<span class="sc">$</span>z, range))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>), <span class="at">cex.main =</span> <span class="fl">1.8</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_slice</span>(st_kde, i, <span class="at">zlim =</span> zlim_month,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">main =</span> <span class="fu">paste</span>(month.name[i], <span class="st">"2023"</span>))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"Monthly fire intensity, July to December 2023"</span>, <span class="at">outer =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">2.1</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>The shared <code>zlim</code> does the job of sparr’s <code>fix.range = TRUE</code>, which takes the same range over every time slice. Without it each month gets its own scale and a quiet December looks as busy as a peak September.</p>
</section>
</section>
<section id="computing-stkde-by-day-of-year" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Computing STKDE by Day of Year</h1>
<section id="computing-spatio-temporal-kde-1" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="computing-spatio-temporal-kde-1"><span class="header-section-number">6.1</span> Computing Spatio-Temporal KDE</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true" href="">Creating the ppp inside the owin</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false" href="">Computing the KDE</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<p>Same steps as the monthly version, with <code>DayofYear</code> as the mark this time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fire_yday_owin <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DayofYear) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>() <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  .[kbb_owin]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  897 points
Average intensity 5.35172e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   10.0   218.0   259.0   247.6   288.0   352.0 

Window: polygonal boundary
308 separate polygons (38 holes)
                   vertices         area relative.area
polygon 1               815  1.16029e+10      6.92e-01
polygon 2                 3  3.24609e+04      1.94e-06
polygon 3                 4  5.42232e+04      3.24e-06
polygon 4                 4  7.99416e+03      4.77e-07
polygon 5                 4  6.30175e+04      3.76e-06
polygon 6                 5  3.82047e+05      2.28e-05
polygon 7                 4  2.39770e+04      1.43e-06
polygon 8                 5  2.22126e+05      1.33e-05
polygon 9 (hole)          3 -3.67129e+04     -2.19e-06
polygon 10 (hole)         3 -3.42876e+04     -2.05e-06
polygon 11                7  1.20124e+06      7.17e-05
polygon 12 (hole)         3 -4.25631e+03     -2.54e-07
polygon 13 (hole)         4 -4.66781e+04     -2.78e-06
polygon 14 (hole)         3 -1.68389e+04     -1.00e-06
polygon 15 (hole)         3 -7.27168e+02     -4.34e-08
polygon 16 (hole)         3 -2.79621e+04     -1.67e-06
polygon 17 (hole)         3 -6.60375e+02     -3.94e-08
polygon 18 (hole)         3 -2.52842e+03     -1.51e-07
polygon 19 (hole)         3 -1.38314e+03     -8.25e-08
polygon 20               11  1.20884e+06      7.21e-05
polygon 21 (hole)         3 -3.27585e+04     -1.95e-06
polygon 22                5  1.74926e+05      1.04e-05
polygon 23 (hole)         3 -3.35348e+02     -2.00e-08
polygon 24 (hole)         3 -4.08226e+03     -2.44e-07
polygon 25 (hole)         3 -1.45480e+04     -8.68e-07
polygon 26 (hole)         3 -3.08962e+02     -1.84e-08
polygon 27                6  1.40188e+05      8.36e-06
polygon 28                5  8.49109e+04      5.07e-06
polygon 29                4  2.39803e+03      1.43e-07
polygon 30                4  8.73093e+03      5.21e-07
polygon 31                5  1.29977e+05      7.75e-06
polygon 32                4  8.60809e+03      5.14e-07
polygon 33                5  2.59087e+05      1.55e-05
polygon 34                4  1.58516e+05      9.46e-06
polygon 35                4  1.29123e+03      7.70e-08
polygon 36                5  1.10066e+05      6.57e-06
polygon 37                4  2.21238e+03      1.32e-07
polygon 38                8  1.54252e+05      9.20e-06
polygon 39                4  8.48082e+03      5.06e-07
polygon 40                4  2.33528e+03      1.39e-07
polygon 41               15  3.11417e+06      1.86e-04
polygon 42               11  2.31185e+06      1.38e-04
polygon 43                4  6.36935e+04      3.80e-06
polygon 44                4  3.76206e+04      2.24e-06
polygon 45                4  6.32582e+04      3.77e-06
polygon 46                4  1.25637e+04      7.50e-07
polygon 47              662  4.61716e+09      2.75e-01
polygon 48                4  6.34172e+03      3.78e-07
polygon 49                5  1.20592e+05      7.19e-06
polygon 50                4  1.73619e+04      1.04e-06
polygon 51                4  2.77155e+04      1.65e-06
polygon 52                5  6.42757e+04      3.83e-06
polygon 53                4  8.43501e+03      5.03e-07
polygon 54                4  7.51117e+03      4.48e-07
polygon 55                9  1.46680e+06      8.75e-05
polygon 56                5  3.36169e+04      2.01e-06
polygon 57                4  6.05506e+04      3.61e-06
polygon 58                4  1.16395e+04      6.94e-07
polygon 59                4  4.13323e+04      2.47e-06
polygon 60                4  1.07759e+04      6.43e-07
polygon 61                4  3.81773e+03      2.28e-07
polygon 62                4  1.67345e+05      9.98e-06
polygon 63                4  3.08386e+04      1.84e-06
polygon 64                4  5.78820e+03      3.45e-07
polygon 65                4  5.41829e+03      3.23e-07
polygon 66                4  2.21673e+03      1.32e-07
polygon 67                4  1.63779e+04      9.77e-07
polygon 68                4  7.63485e+03      4.56e-07
polygon 69                4  8.68147e+03      5.18e-07
polygon 70                4  7.26509e+03      4.33e-07
polygon 71                4  1.02214e+04      6.10e-07
polygon 72                4  1.98251e+04      1.18e-06
polygon 73                4  8.61964e+03      5.14e-07
polygon 74                4  8.19962e+04      4.89e-06
polygon 75                4  3.32475e+03      1.98e-07
polygon 76                4  2.77069e+03      1.65e-07
polygon 77                4  3.94077e+03      2.35e-07
polygon 78                4  6.38963e+04      3.81e-06
polygon 79                4  2.58576e+03      1.54e-07
polygon 80 (hole)         3 -4.14788e+03     -2.47e-07
polygon 81                4  7.20362e+03      4.30e-07
polygon 82                4  6.09823e+03      3.64e-07
polygon 83                4  4.80847e+04      2.87e-06
polygon 84                5  2.12649e+05      1.27e-05
polygon 85 (hole)         4 -1.54678e+04     -9.23e-07
polygon 86                8  1.12373e+06      6.70e-05
polygon 87                4  2.52418e+03      1.51e-07
polygon 88                4  5.29463e+03      3.16e-07
polygon 89                4  7.57252e+03      4.52e-07
polygon 90                6  1.64502e+05      9.81e-06
polygon 91                4  5.95010e+04      3.55e-06
polygon 92                4  1.21987e+04      7.28e-07
polygon 93                4  7.38787e+02      4.41e-08
polygon 94                4  2.73952e+04      1.63e-06
polygon 95                4  4.00173e+03      2.39e-07
polygon 96                4  2.89358e+03      1.73e-07
polygon 97                4  4.37124e+03      2.61e-07
polygon 98 (hole)         3 -1.28102e+04     -7.64e-07
polygon 99               10  2.18651e+06      1.30e-04
polygon 100               4  4.09041e+04      2.44e-06
polygon 101               4  4.18641e+03      2.50e-07
polygon 102               4  1.00965e+04      6.02e-07
polygon 103 (hole)        3 -1.25852e+03     -7.51e-08
polygon 104               4  9.48097e+03      5.66e-07
polygon 105               4  6.97619e+04      4.16e-06
polygon 106               4  1.41599e+03      8.45e-08
polygon 107 (hole)        3 -5.96762e+04     -3.56e-06
polygon 108 (hole)        3 -5.49663e+04     -3.28e-06
polygon 109               4  3.36485e+04      2.01e-06
polygon 110               6  5.27406e+05      3.15e-05
polygon 111               4  4.88529e+04      2.91e-06
polygon 112               5  7.28786e+04      4.35e-06
polygon 113              12  1.03353e+06      6.17e-05
polygon 114               7  2.21577e+05      1.32e-05
polygon 115               4  3.47765e+04      2.07e-06
polygon 116 (hole)        4 -2.29935e+04     -1.37e-06
polygon 117               6  8.13353e+05      4.85e-05
polygon 118 (hole)        3 -3.04392e+04     -1.82e-06
polygon 119               4  4.24745e+03      2.53e-07
polygon 120               4  1.01108e+05      6.03e-06
polygon 121               4  9.41820e+03      5.62e-07
polygon 122               4  1.09569e+04      6.54e-07
polygon 123               4  1.23116e+02      7.35e-09
polygon 124 (hole)        3 -5.35156e+03     -3.19e-07
polygon 125              15  3.89941e+05      2.33e-05
polygon 126 (hole)        3 -1.72223e+04     -1.03e-06
polygon 127               4  2.55805e+04      1.53e-06
polygon 128               8  1.04148e+05      6.21e-06
polygon 129               5  7.50943e+03      4.48e-07
polygon 130               7  4.55629e+05      2.72e-05
polygon 131 (hole)        3 -9.54582e+03     -5.70e-07
polygon 132               4  1.55105e+04      9.25e-07
polygon 133               4  1.76039e+04      1.05e-06
polygon 134               4  5.35495e+03      3.19e-07
polygon 135               4  4.43060e+03      2.64e-07
polygon 136               5  4.06734e+05      2.43e-05
polygon 137              45  1.76360e+07      1.05e-03
polygon 138               4  7.01667e+03      4.19e-07
polygon 139               4  4.25343e+03      2.54e-07
polygon 140               5  2.11664e+05      1.26e-05
polygon 141               4  1.84588e+03      1.10e-07
polygon 142               5  5.00832e+03      2.99e-07
polygon 143               5  7.62514e+04      4.55e-06
polygon 144               4  3.63039e+03      2.17e-07
polygon 145              50  4.89627e+07      2.92e-03
polygon 146             111  1.19754e+08      7.14e-03
polygon 147              16  3.68174e+06      2.20e-04
polygon 148               4  8.24760e+04      4.92e-06
polygon 149               5  5.81024e+04      3.47e-06
polygon 150               4  4.08073e+04      2.43e-06
polygon 151               4  2.89845e+04      1.73e-06
polygon 152               8  1.43483e+06      8.56e-05
polygon 153               4  1.20814e+04      7.21e-07
polygon 154              13  3.67004e+06      2.19e-04
polygon 155              14  3.63429e+06      2.17e-04
polygon 156               4  2.24611e+04      1.34e-06
polygon 157               4  1.55087e+04      9.25e-07
polygon 158               4  2.11021e+05      1.26e-05
polygon 159               4  5.23124e+03      3.12e-07
polygon 160               4  5.60046e+03      3.34e-07
polygon 161               4  1.37815e+04      8.22e-07
polygon 162              19  7.13461e+06      4.26e-04
polygon 163 (hole)        3 -5.67120e+03     -3.38e-07
polygon 164 (hole)        4 -1.00459e+05     -5.99e-06
polygon 165 (hole)        3 -5.37996e+03     -3.21e-07
polygon 166 (hole)        3 -1.82674e+04     -1.09e-06
polygon 167               5  1.38061e+05      8.24e-06
polygon 168 (hole)        3 -3.74646e+04     -2.24e-06
polygon 169 (hole)        3 -3.01697e+04     -1.80e-06
polygon 170 (hole)        3 -5.28210e+04     -3.15e-06
polygon 171               9  1.97808e+06      1.18e-04
polygon 172               4  1.58607e+04      9.46e-07
polygon 173              74  2.12604e+08      1.27e-02
polygon 174               5  1.62979e+05      9.72e-06
polygon 175               4  4.30659e+03      2.57e-07
polygon 176               9  1.53324e+06      9.15e-05
polygon 177               4  9.59752e+03      5.73e-07
polygon 178               4  4.79930e+04      2.86e-06
polygon 179              52  2.23528e+07      1.33e-03
polygon 180              16  2.45920e+06      1.47e-04
polygon 181               4  8.13532e+03      4.85e-07
polygon 182               4  3.38408e+04      2.02e-06
polygon 183               4  2.41837e+04      1.44e-06
polygon 184               4  5.16830e+03      3.08e-07
polygon 185               5  1.61814e+04      9.65e-07
polygon 186               4  6.27571e+03      3.74e-07
polygon 187               5  9.84176e+05      5.87e-05
polygon 188               6  4.20332e+05      2.51e-05
polygon 189               4  2.80854e+05      1.68e-05
polygon 190              10  1.12068e+06      6.69e-05
polygon 191               6  6.73527e+05      4.02e-05
polygon 192               4  4.54882e+04      2.71e-06
polygon 193              12  5.21902e+06      3.11e-04
polygon 194              18  1.73578e+06      1.04e-04
polygon 195               4  3.38083e+04      2.02e-06
polygon 196               4  1.26951e+04      7.57e-07
polygon 197               4  3.62554e+03      2.16e-07
polygon 198              12  3.09025e+06      1.84e-04
polygon 199               4  1.47390e+05      8.79e-06
polygon 200               5  4.05411e+05      2.42e-05
polygon 201               4  4.33229e+04      2.58e-06
polygon 202               5  1.11261e+05      6.64e-06
polygon 203               4  2.74282e+04      1.64e-06
polygon 204              10  1.68501e+06      1.01e-04
polygon 205 (hole)        3 -6.11140e+04     -3.65e-06
polygon 206               4  1.53224e+05      9.14e-06
polygon 207               4  1.93211e+04      1.15e-06
polygon 208               9  1.84908e+06      1.10e-04
polygon 209 (hole)        3 -1.33518e+04     -7.97e-07
polygon 210               4  4.12824e+04      2.46e-06
polygon 211               9  1.09964e+06      6.56e-05
polygon 212               7  8.26344e+05      4.93e-05
polygon 213              13  3.94567e+06      2.35e-04
polygon 214               9  7.82390e+05      4.67e-05
polygon 215               4  4.42404e+04      2.64e-06
polygon 216 (hole)        3 -1.04577e+04     -6.24e-07
polygon 217               4  4.24176e+03      2.53e-07
polygon 218               6  6.77188e+05      4.04e-05
polygon 219               5  3.74156e+05      2.23e-05
polygon 220               4  5.16401e+03      3.08e-07
polygon 221               4  3.24186e+04      1.93e-06
polygon 222              18  7.37432e+06      4.40e-04
polygon 223               5  2.31557e+05      1.38e-05
polygon 224               4  8.61269e+03      5.14e-07
polygon 225               4  9.72139e+03      5.80e-07
polygon 226               4  4.63359e+04      2.76e-06
polygon 227               5  7.51106e+04      4.48e-06
polygon 228               4  5.80096e+04      3.46e-06
polygon 229               4  1.32885e+04      7.93e-07
polygon 230               4  2.83028e+03      1.69e-07
polygon 231               4  2.57186e+04      1.53e-06
polygon 232               5  4.18863e+05      2.50e-05
polygon 233               3  1.72258e+03      1.03e-07
polygon 234               4  2.58773e+03      1.54e-07
polygon 235               4  1.53801e+03      9.18e-08
polygon 236               4  1.20582e+04      7.19e-07
polygon 237               4  1.63886e+04      9.78e-07
polygon 238               4  2.67587e+04      1.60e-06
polygon 239               4  1.59792e+03      9.53e-08
polygon 240               4  2.82709e+03      1.69e-07
polygon 241               4  3.99475e+03      2.38e-07
polygon 242               4  1.47504e+03      8.80e-08
polygon 243              17  3.84724e+06      2.30e-04
polygon 244               4  2.82673e+03      1.69e-07
polygon 245               4  1.01394e+04      6.05e-07
polygon 246 (hole)        7 -6.43668e+04     -3.84e-06
polygon 247 (hole)        3 -9.40962e+01     -5.61e-09
polygon 248               4  1.10610e+04      6.60e-07
polygon 249               4  1.74517e+04      1.04e-06
polygon 250               4  2.82669e+03      1.69e-07
polygon 251               7  5.06540e+05      3.02e-05
polygon 252               4  6.29591e+04      3.76e-06
polygon 253               4  4.54585e+04      2.71e-06
polygon 254               6  9.55597e+05      5.70e-05
polygon 255               7  7.76558e+05      4.63e-05
polygon 256               5  1.71781e+05      1.02e-05
polygon 257               5  2.11515e+05      1.26e-05
polygon 258               7  2.87493e+05      1.72e-05
polygon 259               5  3.95557e+05      2.36e-05
polygon 260              27  1.62392e+07      9.69e-04
polygon 261               4  4.43585e+03      2.65e-07
polygon 262               4  6.27477e+03      3.74e-07
polygon 263              10  1.30987e+06      7.82e-05
polygon 264               9  2.25682e+06      1.35e-04
polygon 265               4  1.45948e+04      8.71e-07
polygon 266               4  1.21931e+04      7.27e-07
polygon 267               9  1.17483e+06      7.01e-05
polygon 268               4  2.20546e+04      1.32e-06
polygon 269               5  3.03395e+04      1.81e-06
polygon 270               4  9.35222e+03      5.58e-07
polygon 271               4  1.03499e+05      6.18e-06
polygon 272               6  2.34707e+04      1.40e-06
polygon 273               4  7.75326e+03      4.63e-07
polygon 274               4  1.23210e+03      7.35e-08
polygon 275               4  2.71061e+03      1.62e-07
polygon 276               4  2.80917e+04      1.68e-06
polygon 277               4  1.97108e+03      1.18e-07
polygon 278               4  4.43561e+03      2.65e-07
polygon 279               4  5.11117e+03      3.05e-07
polygon 280               6  4.86779e+05      2.90e-05
polygon 281               5  8.12261e+04      4.85e-06
polygon 282               4  2.50739e+04      1.50e-06
polygon 283               4  2.71022e+03      1.62e-07
polygon 284               6  3.33963e+05      1.99e-05
polygon 285              14  3.34010e+06      1.99e-04
polygon 286               4  4.31165e+03      2.57e-07
polygon 287               4  2.84259e+04      1.70e-06
polygon 288               4  2.50478e+04      1.49e-06
polygon 289               5  1.72690e+05      1.03e-05
polygon 290               4  1.37933e+04      8.23e-07
polygon 291               4  3.08058e+03      1.84e-07
polygon 292               5  1.34807e+05      8.04e-06
polygon 293               5  4.43080e+04      2.64e-06
polygon 294              13  2.22861e+06      1.33e-04
polygon 295               4  4.19032e+03      2.50e-07
polygon 296              11  1.04351e+06      6.23e-05
polygon 297               4  1.49419e+04      8.91e-07
polygon 298               4  7.14815e+03      4.26e-07
polygon 299               4  8.08482e+04      4.82e-06
polygon 300               6  1.92382e+05      1.15e-05
polygon 301               4  2.08873e+05      1.25e-05
polygon 302               4  3.08068e+04      1.84e-06
polygon 303               5  6.62422e+04      3.95e-06
polygon 304               7  1.05373e+06      6.29e-05
polygon 305               4  2.57200e+04      1.53e-06
polygon 306               4  1.22325e+05      7.30e-06
polygon 307               6  2.33212e+05      1.39e-05
polygon 308               4  1.44038e+05      8.59e-06
enclosing rectangle: [512010.2, 928094.9] x [9621873, 9833973] units
                     (416100 x 212100 units)
Window area = 1.6761e+10 square units
Fraction of frame area: 0.19</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<p><code>spattemp.density()</code> again with its default bandwidths, now on a time axis measured in days.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>kde_yday <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 19139.22 (spatial)
  lambda = 6.4506 (temporal)

No. of observations
  897 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.2, 928094.9] x [9621873, 9833973]

Temporal bound
  [10, 352]

Evaluation
  128 x 128 x 343 trivariate lattice
  Density range: [2.254954e-28, 1.864846e-12]</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Issue I hit
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book’s next line is <code>plot(kde_yday)</code> and it produces 343 separate plots, one for every day in the temporal bound. The rendered chapter page has 343 image tags in a row. I know because I fetched it and counted.</p>
<p>Do not do that. <code>plot()</code> on a sparr object accepts a <code>tselect</code> argument for which times to draw, and <code>plot_slice()</code> above takes one time the same way. Six days from the dry season say everything 343 would.</p>
</div>
</div>
</section>
<section id="plotting-the-spatio-temporal-kde-object-1" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="plotting-the-spatio-temporal-kde-object-1"><span class="header-section-number">6.2</span> Plotting the Spatio-Temporal KDE Object</h2>
<p>Six days at fifteen-day steps, from 1 August to 15 October. The colour key is now the share of the year’s detections per square metre per day (the peak is about 1.9e-12), and <code>zlim_yday</code> gives all six panels one scale.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>zlim_yday <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">sapply</span>(kde_yday<span class="sc">$</span>z, range))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">213</span>, <span class="dv">228</span>, <span class="dv">243</span>, <span class="dv">258</span>, <span class="dv">273</span>, <span class="dv">288</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>), <span class="at">cex.main =</span> <span class="fl">1.8</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> days) {</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_slice</span>(kde_yday, d, <span class="at">zlim =</span> zlim_yday,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Day "</span>, d, <span class="st">" ("</span>, <span class="fu">format</span>(<span class="fu">as.Date</span>(<span class="st">"2023-01-01"</span>) <span class="sc">+</span> d <span class="sc">-</span> <span class="dv">1</span>, <span class="st">"%d %b"</span>), <span class="st">")"</span>))</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"Daily fire intensity, default bandwidths"</span>, <span class="at">outer =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">2.1</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="computing-stkde-by-day-of-year-improved-method" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Computing STKDE by Day of Year: Improved Method</h1>
<section id="computing-spatio-temporal-kde-2" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="computing-spatio-temporal-kde-2"><span class="header-section-number">7.1</span> Computing Spatio-Temporal KDE</h2>
<p>The two defaults above came from a rule of thumb. <code>BOOT.spattemp()</code> of <strong>sparr</strong> picks them by bootstrap instead, minimising the estimated error of the whole surface.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true" href="">Choosing the bandwidths by bootstrap</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false" href="">Refitting with the rounded bandwidths</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<p><code>set.seed()</code> fixes the resampling so the result repeats, then <code>BOOT.spattemp()</code> searches over both bandwidths at once.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bw_boot <span class="ot">&lt;-</span> <span class="fu">BOOT.spattemp</span>(fire_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Initialising...Done.
Optimising...
h = 19139.22 ; lambda = 15.33986 
h = 21053.14 ; lambda = 15.33986 
h = 19139.22 ; lambda = 1929.261 
h = 19617.7 ; lambda = 972.3006 
h = 19856.94 ; lambda = 493.8202 
h = 19976.56 ; lambda = 254.58 
h = 20036.37 ; lambda = 134.96 
h = 20066.27 ; lambda = 75.14991 
h = 20081.22 ; lambda = 45.24488 
h = 20088.7 ; lambda = 30.29237 
h = 20103.65 ; lambda = 0.3873488 
h = 20092.44 ; lambda = 22.81612 
h = 22006.36 ; lambda = 22.81612 
h = 23439.93 ; lambda = 26.55424 
h = 24400.63 ; lambda = 19.07799 
h = 26554.73 ; lambda = 17.20892 
h = 28941.52 ; lambda = 28.42331 
h = 26969.42 ; lambda = 25.15245 
h = 30084.22 ; lambda = 15.80713 
h = 33406.36 ; lambda = 10.43357 
h = 29669.52 ; lambda = 7.863605 
h = 27644.45 ; lambda = 20.83024 
h = 31173.94 ; lambda = 19.42844 
h = 33483.55 ; lambda = 20.53819 
h = 35923.32 ; lambda = 15.51509 
h = 40062.76 ; lambda = 12.85751 
h = 43462.09 ; lambda = 17.58858 
h = 50151.02 ; lambda = 18.4793 
h = 50041.3 ; lambda = 9.907893 
h = 45901.86 ; lambda = 12.56547 
h = 49301.19 ; lambda = 17.29654 
h = 53920.41 ; lambda = 19.51605 
h = 46861.42 ; lambda = 22.31965 
h = 46141.75 ; lambda = 15.00401 
h = 51980.85 ; lambda = 14.71197 
h = 45591.78 ; lambda = 16.86943 
Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bw_boot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          h      lambda 
45591.77993    16.86943 </code></pre>
</div>
</div>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<p><code>spattemp.density()</code> again, with <code>h</code> and <code>lambda</code> passed in by hand.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>kde_yday_boot <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">h =</span> <span class="dv">45000</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">lambda =</span> <span class="dv">17</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday_boot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 45000 (spatial)
  lambda = 17 (temporal)

No. of observations
  897 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.2, 928094.9] x [9621873, 9833973]

Temporal bound
  [10, 352]

Evaluation
  128 x 128 x 343 trivariate lattice
  Density range: [2.142156e-16, 1.024812e-12]</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>The bootstrap is slow. It prints thirty odd iterations before settling, and each one refits the surface. This is the chunk that made me set <code>freeze: true</code> at the top of the file, otherwise every render would rerun it.</p>
<p>The book’s bootstrap lands at h of 9000 and lambda of 19, and the chapter rounds them before use. Mine lands somewhere else, about 45.6 km and 17 days. Those are different samples, so I round my own numbers to 45000 and 17 rather than borrow the book’s.</p>
<p>Rounding is the right call either way. Six decimal places from a bootstrap pretend to a precision the method does not have.</p>
</div>
</div>
</section>
<section id="plotting-the-output-spatio-temporal-kde" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="plotting-the-output-spatio-temporal-kde"><span class="header-section-number">7.2</span> Plotting the Output Spatio-Temporal KDE</h2>
<p>The same six days drawn from the bootstrap surface. The unit is the same as the default version above, but this figure has its own <code>zlim_boot</code>, so compare patterns between the two figures rather than colours.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>zlim_boot <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">sapply</span>(kde_yday_boot<span class="sc">$</span>z, range))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>), <span class="at">cex.main =</span> <span class="fl">1.8</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> days) {</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_slice</span>(kde_yday_boot, d, <span class="at">zlim =</span> zlim_boot,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Day "</span>, d, <span class="st">" ("</span>, <span class="fu">format</span>(<span class="fu">as.Date</span>(<span class="st">"2023-01-01"</span>) <span class="sc">+</span> d <span class="sc">-</span> <span class="dv">1</span>, <span class="st">"%d %b"</span>), <span class="st">")"</span>))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"Daily fire intensity, bootstrap bandwidths"</span>, <span class="at">outer =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">2.1</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>Same six days, two bandwidth choices, one figure above the other so they can be compared.</p>
<p>The default gave h of about 19 km and lambda of about 6 days. The bootstrap gave 45 km and 17 days. So the bootstrap smooths harder on both axes, more than twice the spatial bandwidth and nearly three times the temporal one.</p>
<p>Both sets of maps tell the same story. A hotspot starts in west Bangka in early August and moves to the south of the island by late September. Belitung stays quiet throughout.</p>
<p>The difference is how they tell it. The default keeps the hotspot tight and Belitung dark. The bootstrap spreads the same hotspot across half of Bangka, halves its peak (the summaries give a maximum of 1.9e-12 for the default and 1.0e-12 for the bootstrap), and lets Belitung glow, because a 45 km kernel reaches across the strait.</p>
<p>Which is right depends on the question. For where fires happen, the default’s sharper space is more useful. For when, the bootstrap’s smoother time is. The bootstrap minimises one overall error and does not know which question I am asking.</p>
<p>The book got 9 km and 19 days on its 741 points, which is sharper space than its own default. Same method, different sample, opposite call on the spatial axis. Bandwidth is a property of the data in hand, not of the method.</p>
</div>
</div>
</section>
</section>
<section id="spatio-temporal-point-patterns-analysis-stpp-methods" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Spatio-Temporal Point Patterns Analysis: stpp Methods</h1>
<p>The KDE is first order. It says where and when fires are dense. The K function is second order. It says whether fires happen near other fires, in space and time together, more than they would if location and timing were unrelated.</p>
<section id="preparing-spatio-temporal-point-process-object-of-stpp" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="preparing-spatio-temporal-point-process-object-of-stpp"><span class="header-section-number">8.1</span> Preparing Spatio-Temporal Point Process Object of stpp</h2>
<p>stpp wants a plain three-column matrix, x, y and an integer time. <code>st_coordinates()</code> of <strong>sf</strong> pulls out the projected x and y, and <code>as.3dpoints()</code> of <strong>stpp</strong> wraps the three columns as an <code>stpp</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(fire_sf)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>fire_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> coords[, <span class="dv">1</span>],</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> coords[, <span class="dv">2</span>],</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">t =</span> fire_sf<span class="sc">$</span>DayofYear)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>fire_stpp <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(fire_df)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "stpp"</code></pre>
</div>
</div>
<p>stpp’s own <code>plot()</code> for this object gives two panels titled “xy-locations” and “cumulative number”, with axes labelled x, y and t and a stretched map. I draw the same two panels by hand with base <code>plot()</code>, from <code>fire_df</code>, which holds the same three columns. The map uses <code>asp = 1</code> so a kilometre east is as long as a kilometre north, and the count is a step line.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">cex.main =</span> <span class="fl">1.3</span>, <span class="at">cex.lab =</span> <span class="fl">1.1</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_df<span class="sc">$</span>x, fire_df<span class="sc">$</span>y, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Fire locations"</span>, <span class="at">xlab =</span> <span class="st">"Easting (m)"</span>, <span class="at">ylab =</span> <span class="st">"Northing (m)"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">sort</span>(fire_df<span class="sc">$</span>t), <span class="fu">seq_len</span>(<span class="fu">nrow</span>(fire_df)), <span class="at">type =</span> <span class="st">"s"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Cumulative fires through 2023"</span>, <span class="at">xlab =</span> <span class="st">"Day of year"</span>, <span class="at">ylab =</span> <span class="st">"Fires"</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>The left panel places every detection in UTM metres, Bangka on the left and Belitung on the right. The right panel counts the fires cumulatively through the year, and the dry season shows as the steep climb from about day 200.</p>
</section>
<section id="computing-spatio-temporal-k-function" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="computing-spatio-temporal-k-function"><span class="header-section-number">8.2</span> Computing Spatio-Temporal K-Function</h2>
<p><code>STIKhat()</code> of <strong>stpp</strong> estimates the space-time K function on a default grid of spatial and temporal distances.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>kbb_stik <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Issue I hit
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book’s <code>plotK(kbb_stik)</code> rendered to nothing. The chunk ran, the page had an empty tab where the surface should be.</p>
<p>The function source explains it. <code>plotK()</code> closes the current graphics device and opens a new one for its own layout. Knitr was recording into the device that got closed, so the plot went to a window nobody saw.</p>
<p>The fix is to skip <code>plotK()</code> and draw the surface myself. The object holds <code>Khat</code>, the estimate, and <code>Ktheo</code>, the value expected if space and time were independent, both over <code>dist</code> and <code>times</code>. I plot the difference, since that is what the reading below is about, and I get to label the axes properly.</p>
</div>
</div>
<p><code>filled.contour()</code> from base <strong>graphics</strong> draws the difference as a coloured surface, and <code>contour()</code> adds labelled lines on top. <code>STIKhat()</code> returns distances in metres, so I divide <code>u</code> by 1000 to put the x axis in kilometres. The colour key, titled “K excess”, is <code>Khat</code> minus <code>Ktheo</code> in the K function’s own units, square metres times days.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-14-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-1" role="tab" aria-controls="tabset-14-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-14-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-2" role="tab" aria-controls="tabset-14-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-14-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-14-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-14-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> kbb_stik<span class="sc">$</span>dist <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> kbb_stik<span class="sc">$</span>times</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>k_excess <span class="ot">&lt;-</span> kbb_stik<span class="sc">$</span>Khat <span class="sc">-</span> kbb_stik<span class="sc">$</span>Ktheo</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.main =</span> <span class="fl">1.3</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">filled.contour</span>(u, v, k_excess,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">color.palette =</span> <span class="cf">function</span>(n) <span class="fu">hcl.colors</span>(n, <span class="st">"YlOrRd"</span>, <span class="at">rev =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">"u, spatial distance (km)"</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">"v, temporal distance (days)"</span>,</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">main =</span> <span class="st">"Space-time K minus the independence expectation"</span>,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">key.title =</span> <span class="fu">title</span>(<span class="at">main =</span> <span class="st">"K excess"</span>, <span class="at">cex.main =</span> <span class="fl">0.9</span>),</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">plot.axes =</span> {</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">axis</span>(<span class="dv">1</span>); <span class="fu">axis</span>(<span class="dv">2</span>)</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">contour</span>(u, v, k_excess, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey10"</span>, <span class="at">lwd =</span> <span class="fl">0.6</span>,</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labcex =</span> <span class="fl">0.9</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>               })</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="guide-to-interpreting-the-plot" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="guide-to-interpreting-the-plot"><span class="header-section-number">8.3</span> Guide to Interpreting the Plot</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning diary
</div>
</div>
<div class="callout-body-container callout-body">
<p>This took me a while to read, so here is the version I wish the book had given.</p>
<p>The plot is a surface over two axes. <code>u</code> is distance in space, which I plotted in kilometres, and <code>v</code> is distance in days. The height at any point is how many more fires sit within <code>u</code> kilometres and <code>v</code> days of a typical fire than you would expect if space and time were independent. That is the <code>Khat</code> minus <code>Ktheo</code> I drew above.</p>
<p>A surface that rises steeply near the origin, at small <code>u</code> and small <code>v</code>, means fires happen close to other fires and soon after them. That is space-time clustering. A flat surface means no such interaction.</p>
<p>The word inhomogeneous in the name is a promise the call above does not keep. <code>STIKhat()</code> only corrects for varying intensity if you pass it a <code>lambda</code>, the intensity at every point. The book does not and neither did I. So it falls back to a constant, the point count divided by the space-time volume, and this is really a homogeneous K.</p>
<p>The surface shows it. The excess is positive everywhere and keeps climbing with both <code>u</code> and <code>v</code>, out to 45 km and 80 days. Clustering that keeps growing with scale is the dry season and the fire belt of Bangka showing through. The KDE already found that. It is not fires near fires setting off more fires.</p>
<p>A proper inhomogeneous version would feed the spatio-temporal KDE back in as <code>lambda</code>. That is the version I want for the take-home.</p>
</div>
</div>
</section>
</section>
<section id="beyond-the-exercise" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Beyond the Exercise</h1>
<p>Three things I wanted to check that the chapter does not.</p>
<section id="does-the-type-filter-change-the-answer" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="does-the-type-filter-change-the-answer"><span class="header-section-number">9.1</span> Does the Type Filter Change the Answer</h2>
<p>I dropped volcanoes and static sources while preparing the data. Worth showing what they would have done. The same <code>st_as_sf()</code>, <code>st_transform()</code> and <code>st_filter()</code> chain runs on the unfiltered table, and a <code>tibble()</code> sets the two counts side by side.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fire_all_kbb <span class="ot">&lt;-</span> fire_all <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_filter</span>(<span class="fu">st_as_sf</span>(kbb_sf))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">kept =</span> <span class="fu">c</span>(<span class="st">"all types"</span>, <span class="st">"type 0 only"</span>),</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">detections =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(fire_all_kbb), <span class="fu">nrow</span>(fire_sf)),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropped =</span> detections[<span class="dv">1</span>] <span class="sc">-</span> detections</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  kept        detections dropped
  &lt;chr&gt;            &lt;int&gt;   &lt;int&gt;
1 all types          898       0
2 type 0 only        897       1</code></pre>
</div>
</div>
<p><code>count()</code> on the unfiltered points shows which types were there to drop.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>fire_all_kbb <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(type, <span class="at">name =</span> <span class="st">"detections"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
   type detections
  &lt;dbl&gt;      &lt;int&gt;
1     0        897
2     2          1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Alternative explored
</div>
</div>
<div class="callout-body-container callout-body">
<p>For Bangka Belitung specifically the filter removes exactly one row, a single type 2 static-source detection, taking 898 down to 897. The maps above would look the same either way. There are no volcanoes on the island.</p>
<p>That is a finding, not a failure. The filter was cheap, it was justified by the data dictionary, and for a Kalimantan regency in the take-home it will matter a great deal more, because Kalimantan has oil and gas flares and other industrial heat sources that FIRMS tags as type 2. Better to have the habit before it matters.</p>
</div>
</div>
</section>
<section id="does-detection-confidence-change-the-answer" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="does-detection-confidence-change-the-answer"><span class="header-section-number">9.2</span> Does Detection Confidence Change the Answer</h2>
<p>MODIS reports a confidence score from 0 to 100 on every detection. The book ignores it. <code>quantile()</code> shows how the scores spread.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(fire_sf<span class="sc">$</span>confidence, <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
   0   55   67   76  100 </code></pre>
</div>
</div>
<p><code>filter()</code> keeps the detections at 80 or above, and the <code>tibble()</code> compares the counts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>fire_hi <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span> <span class="fu">filter</span>(confidence <span class="sc">&gt;=</span> <span class="dv">80</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">threshold =</span> <span class="fu">c</span>(<span class="st">"all"</span>, <span class="st">"confidence &gt;= 80"</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">detections =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(fire_sf), <span class="fu">nrow</span>(fire_hi))</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  threshold        detections
  &lt;chr&gt;                 &lt;int&gt;
1 all                     897
2 confidence &gt;= 80        164</code></pre>
</div>
</div>
<p>The subset goes through the same <code>as.ppp()</code> and <code>spattemp.density()</code> steps, with the bootstrap bandwidths from above so that only the data change.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>fire_hi_owin <span class="ot">&lt;-</span> fire_hi <span class="sc">%&gt;%</span> <span class="fu">select</span>(DayofYear) <span class="sc">%&gt;%</span> <span class="fu">as.ppp</span>() <span class="sc">%&gt;%</span> .[kbb_owin]</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>kde_hi <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_hi_owin, <span class="at">h =</span> <span class="dv">45000</span>, <span class="at">lambda =</span> <span class="dv">17</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Three of the six days, every detection on the top row and the high confidence subset below. <code>zlim_conf</code> is the range over both surfaces, so all six panels share one colour scale, in the same share of detections per square metre per day as before.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-15-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-1" role="tab" aria-controls="tabset-15-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-15-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-2" role="tab" aria-controls="tabset-15-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-15-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-15-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-15-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>zlim_conf <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">c</span>(<span class="fu">sapply</span>(kde_yday_boot<span class="sc">$</span>z, range), <span class="fu">sapply</span>(kde_hi<span class="sc">$</span>z, range)))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>), <span class="at">cex.main =</span> <span class="fl">1.8</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> days[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>)]) {</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_slice</span>(kde_yday_boot, d, <span class="at">zlim =</span> zlim_conf,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"All, day"</span>, d))</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_slice</span>(kde_hi, d, <span class="at">zlim =</span> zlim_conf,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Conf &gt;= 80, day"</span>, d))</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"All fires against confidence 80 and above, one scale"</span>, <span class="at">outer =</span> <span class="cn">TRUE</span>, <span class="at">cex =</span> <span class="fl">2.1</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Alternative explored
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eighty is FIRMS’s own line for high confidence, and it is a hard one. Half the detections sit below 67 and only 164 of 897 clear 80, so the bottom row is drawn from under a fifth of the data.</p>
<p>Top row is every detection, bottom row is the high confidence subset. Even with four fifths of the points gone the hotspots sit in the same places and move the same way through the season. Both surfaces are densities that integrate to one over space and time, so the smaller subset does not simply come out dimmer. What would matter is the bright patches moving, and they do not.</p>
<p>That is a useful sanity check. If the high confidence subset had shown a completely different pattern, the full-data maps would have been driven by noise. It does not, so they are not. The question of which threshold to use is a data quality decision the chapter skips, and for the take-home it has to be stated and justified.</p>
</div>
</div>
</section>
<section id="is-it-space-time-or-both" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="is-it-space-time-or-both"><span class="header-section-number">9.3</span> Is It Space, Time, or Both</h2>
<p>The K surface above says whether there is space-time interaction. It does not say whether there would have been spatial clustering anyway, with time ignored. Exercise 2’s tools answer that. <code>unmark()</code> drops the day marks, and <code>envelope()</code> of <strong>spatstat</strong> simulates 39 random patterns in the same window around <code>Lest</code>, with <code>global = TRUE</code> for a simultaneous envelope.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fire_sp <span class="ot">&lt;-</span> <span class="fu">unmark</span>(fire_yday_owin)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>L_sp <span class="ot">&lt;-</span> <span class="fu">envelope</span>(fire_sp, Lest, <span class="at">nsim =</span> <span class="dv">39</span>, <span class="at">rank =</span> <span class="dv">1</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">global =</span> <span class="cn">TRUE</span>, <span class="at">correction =</span> <span class="st">"Ripley"</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The plot shows L(d) minus d against distance in metres. The solid line is the observed pattern, the dashed line at zero is complete spatial randomness, and the grey band is the global envelope.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-16-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-1" role="tab" aria-controls="tabset-16-1" aria-selected="true" href="">The Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-16-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-2" role="tab" aria-controls="tabset-16-2" aria-selected="false" href="">The Code</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-16-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex03_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-16-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-16-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.main =</span> <span class="fl">1.3</span>, <span class="at">cex.sub =</span> <span class="fl">1.1</span>, <span class="at">cex.lab =</span> <span class="fl">1.1</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(L_sp, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">xlab =</span> <span class="st">"d (m)"</span>, <span class="at">ylab =</span> <span class="st">"L(d) - r"</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Spatial L function, time ignored, global envelope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Alternative explored
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read the two together. The L function says the fires cluster in space when you collapse the whole year onto one map. The STIK surface says whether there is <em>additional</em> clustering once you also ask about time.</p>
<p>If both show clustering, fires are drawn to the same places and also happen in bursts. If only the spatial one does, the bursts are just the dry season, and nearby fires are not setting each other off.</p>
<p>Here both show clustering. But the K surface was computed with a constant intensity, so the dry season is still inside it. The honest reading is that fires cluster in space and cluster in time, and whether the two interact stays untested until <code>lambda</code> goes in.</p>
<p>The chapter runs the second test without the first, so it cannot make that distinction. Running both is what makes the space-time result readable.</p>
</div>
</div>
</section>
</section>
<section id="limitations" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Limitations</h1>
<ul>
<li>GADM’s boundary and the book’s kelurahan shapefile are different sources, so the observation window is not identical to the book’s and the point count differs.</li>
<li>MODIS detects heat, not fire. A detection is a hot pixel about a kilometre across, so a single fire may appear as several points and several fires as one.</li>
<li>Cloud cover hides fires. Missing days in the dry season may be weather, not absence of fire.</li>
<li>Two satellites, Terra and Aqua, pass at different times of day, so the daily record is really two snapshots, not continuous.</li>
<li>The bootstrap bandwidths optimise one overall error and do not know whether the analyst cares more about where or about when.</li>
<li>The STIK surface has no envelope in this exercise, so a high contour is suggestive, not tested. It also used a constant intensity, so it is not yet the inhomogeneous version its name claims.</li>
</ul>
</section>
<section id="reflections" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Reflections</h1>
<p>Five things I am taking from this one.</p>
<p><strong>The <code>type</code> column was the most important thing in the file and the chapter never mentions it.</strong> Volcanoes, gas flares and offshore pixels are all in the same table as vegetation fires, and FIRMS labels them. Keeping everything and calling it forest fires would have been wrong, and for Kalimantan in the take-home it would have been badly wrong. Reading the data dictionary before the data is a habit that starts here, and I mean to keep it.</p>
<p><strong>Two downloads failed before one worked.</strong> A 553 MB shapefile at 44 kilobytes a second, then a bundle that arrived truncated with Indonesia in the missing part. The per-country FIRMS file and GADM level 2 got me the same analysis from 9 MB total. Worth remembering that the book’s data path is one route, not the only one.</p>
<p><strong>Bandwidth is now two numbers, and the selector does not know which one I care about.</strong> The default and the bootstrap disagreed on both. On my data the bootstrap smoothed harder on each, on the book’s data it went sharper in space. Neither is wrong. The right choice depends on whether the question is where or when, and no selector can know that.</p>
<p><strong>A plot call can be a mistake.</strong> <code>plot(kde_yday)</code> with no time selected gives 343 images. <code>plotK()</code> gives none, because it swaps graphics devices under knitr. The first I caught because the book’s own rendered page is the warning. The second I caught only because I read my own render before pushing it.</p>
<p><strong>The space-time K function needs two things next to it, the plain spatial L and an intensity.</strong> On its own it says there is clustering. Next to the L function from Exercise 2 it can say whether that clustering is more than the dry season. Without a <code>lambda</code> it cannot even ask, because inhomogeneous is just a word in the function name until you pass one. The chapter does neither, and I think that is a gap.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>